#!/usr/bin/env bash
# Regenerate a hash-pinned constraints file for a specific ESPHome
# version (SC.3). Runs `pip-compile --generate-hashes --strip-extras`
# inside a Linux/amd64 python:3.11-slim container so the resulting
# hashes are the ones workers will actually download.
#
# Usage:
#   bash scripts/regen-esphome-constraints.sh 2026.4.0
#   bash scripts/regen-esphome-constraints.sh 2026.4.0 2026.3.3 2026.3.2
#
# Writes to ha-addon/client/esphome-constraints/<version>.txt for
# each version on the command line. Commit the result + bump
# ha-addon/client/IMAGE_VERSION so the new constraints ship.
set -euo pipefail

if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <esphome-version> [<esphome-version> ...]" >&2
    exit 1
fi

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT_DIR="$REPO_ROOT/ha-addon/client/esphome-constraints"
mkdir -p "$OUT_DIR"

for VERSION in "$@"; do
    echo "▶ Regenerating esphome-constraints/${VERSION}.txt ..."
    TMPDIR=$(mktemp -d)
    trap 'rm -rf "$TMPDIR"' EXIT
    echo "esphome==${VERSION}" > "$TMPDIR/input.in"

    docker run --rm \
        --platform linux/amd64 \
        -v "$TMPDIR:/work" \
        -w /work \
        python:3.11-slim \
        bash -c "
            set -e
            apt-get update -qq && apt-get install -y -qq --no-install-recommends build-essential git > /dev/null
            pip install --quiet --no-cache-dir 'pip-tools>=7.4'
            pip-compile \
                --generate-hashes \
                --strip-extras \
                --output-file=output.txt \
                input.in
        "

    # Prepend a banner so the file's purpose is obvious to anyone
    # stumbling on it in a code review.
    {
        echo "# Hash-pinned constraints for esphome==${VERSION} (SC.3)."
        echo "# Generated by scripts/regen-esphome-constraints.sh ${VERSION}."
        echo "# Do not edit by hand — rerun the script against the same version."
        echo "#"
        cat "$TMPDIR/output.txt"
    } > "$OUT_DIR/${VERSION}.txt"
    rm -rf "$TMPDIR"
    trap - EXIT

    echo "  ✅ wrote $OUT_DIR/${VERSION}.txt"
done

echo ""
echo "Done. Remember to bump ha-addon/client/IMAGE_VERSION so workers"
echo "pull a new image with the updated constraints baked in."
